version: "3"
services:
  frontend:
    image: frontend-app
    ports:
      - "8000:5000"
  backend:
    image: backend-app
    ports:
      - "8080:8080"
    depends_on:
     - redis
     - mongo
  redis:
    image: redis
  mongo:
    image: mongo